### ISSUE TITLE
Update system diagram to include rendering pipeline work

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/openhistoricalmap-docker#1]
Doc:
https://docs.google.com/drawings/d/1hK6TkNQIg-JZjfFxOSwB_MsO66IzoZVU228B12wb_1M/edit

**Comment by sethfitz** [comment]
OpenMapTiles added as its own blob (separately managed outside of ECS), Nominatim-related components removed:

![image](https://user-images.githubusercontent.com/45/53908593-8cee8700-4004-11e9-8aa3-a4db97ae5014.png)
