### ISSUE TITLE
Replace Leaflet with Mapbox GL

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/openhistoricalmap-docker#10]
Per discussion in person this AM, while working on #5, Seth will also make the necessary changes to replace Leaflet with Mapbox GL on OHM homepage. We think this should fit within existing infrastructure scope hours. 

And note that this doesn't touch the pending implementation scoping and doing of date filtering, but it does get us the vector tiles in the place where we will eventually need to do that date filtering.

**Comment by sethfitz** [comment]
Making headway, courtesy of https://github.com/mapbox/mapbox-gl-leaflet, which is allowing me to re-use all of the existing controls.

![image](https://user-images.githubusercontent.com/45/55125413-d7749800-50c6-11e9-967b-56d14d022a5e.png)

**Comment by jeffreyameyer** [comment]
Woo--hoo!!!!
