### ISSUE TITLE
Email Server set up for new users

### ISSUE THREAD

**Issue by jimmyrocks** [OpenHistoricalMap/openhistoricalmap-docker#18]
When a new user is created, a confirmation email is sent
If no server is set in the variables, the email will not be sent, and the user cannot be validated (made active)
We need to identify a server to use and set it in the environment variables.

**Comment by sethfitz** [comment]
Environment variable support implemented in https://github.com/OpenHistoricalMap/ohm-website/pull/34

Amazon SES credentials created and registered in Parameter Store. ECS Task Definition updated to use values from Parameter Store and expose to Rails.

**Comment by sethfitz** [comment]
Service limit increase for SES sent in order to get us out of the sandbox so we can send verification emails.

**Comment by sethfitz** [comment]
ECS Task Definition created for [Delayed Job](https://github.com/collectiveidea/delayed_job/tree/v4.1.5), which handles queued tasks, e.g. sending emails.

CodePipeline updated to deploy updated `jobs` tasks alongside `website`.

**Comment by sethfitz** [comment]
"Forgot my password" emails send now.

![image](https://user-images.githubusercontent.com/45/53923189-39902f00-402c-11e9-9772-2c77019296cc.png)

The return address on emails is temporarily set to me, as it needs to be verified within the SES Management Console.

**Comment by sethfitz** [comment]
(Registering a new account does not appear to send email / require validation right now.)
