### ISSUE TITLE
Query/infopanel question

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/openhistoricalmap-docker#20]
Jeff asked me whether we could work on info panel updates alongside DevSeed's upcoming work on Nominatim. So I'm looking more closely at that and had a question about whether there's a first-run super-low-effort thing to do:

On the Dev AWS site has an info panel that queries OSM, shows features that don’t exist and then tries to link to them with node IDs from OSM but on OHM infrastructure, which leads of course to 404s.

That's about to happen here if I click any of these links:
![image](https://user-images.githubusercontent.com/1423200/62334926-7e56af80-b47e-11e9-8d02-c62ec47f4879.png)

In the Parameter Store as shown [here](https://github.com/OpenHistoricalMap/openhistoricalmap-docker#website), we have:
```
{
          "name": "OSM_overpass_url",
          "value": "//overpass-api.de/api/interpreter"
        },
```

Is a first step in getting info panel working simply to replace that parameter with the production OHM Overpass API URL, which as of a week or two ago is now running over https?

**Comment by danrademacher** [comment]
For the record, we'd change that to https://overpass-api.openhistoricalmap.org/api/interpreter

**Comment by danrademacher** [comment]
Hmm apparently not. I went into AWS ECS definition and I see we are already using correct Overpass:
![image](https://user-images.githubusercontent.com/1423200/62336513-6b93a900-b485-11e9-8517-4099409b1df7.png)

And then I thought, duh, maybe these links are 404ing because we're not hosting the DB

So something like this:
![image](https://user-images.githubusercontent.com/1423200/62336831-004ad680-b487-11e9-8c6d-070e68305434.png)
links to
http://openhistoricalmap-1936150974.us-east-1.elb.amazonaws.com/node/262639984

So maybe that should be:
http://openhistoricalmap.org/node/262639984

Nope, nothing there. But here's an ice cream store:
https://www.openstreetmap.org/node/262639984

**Comment by sethfitz** [comment]
(I've been fiddling with this.)

`OSM_overpass_url` (and `OSM_nominatim_url`) are both used at build-time to output JavaScript with appropriate parameters, so changing it in the ECS Task Definition has no effect (sadly).

I've moved the values into Parameter Store (using the same names), updated the CodeBuild environment to load them, the buildspec to pass them into the build (as `--build-arg`), and updated the `codebuild-website-service-role` IAM role to grant it access to parameters (`ssm:getParameters` et al).

The build pipeline is running now. I suspect that I may need to update the `Dockerfile` to explicitly specify that they can be provided as build args, but I want to see how this does first.

(I'm covering Nominatim in this to save future-us from some pain.)

**Comment by danrademacher** [comment]
Oh great! So my original hunch was on-target sorta. That's always gratifying ;)

**Comment by sethfitz** [comment]
Yes, very much so! I didn't expect it to be a build-time thing either.

**Comment by sethfitz** [comment]
Alas, it looks like I did need to update the Dockerfile: https://github.com/OpenHistoricalMap/openhistoricalmap-docker/commit/134bc69c875e4b957e6e7c902d024cc60493a24e

**Comment by sethfitz** [comment]
![image](https://user-images.githubusercontent.com/45/62338406-46a33400-b48d-11e9-8700-b214f0e7aabb.png)

The OHM Overpass doesn't seem to like having 2 concurrent requests made to it (1 for nearby, 1 for enclosing features), but it's working on the OHM website end of things.
