### ISSUE TITLE
AWS deploy

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/openhistoricalmap-docker#5]
I suspect this should be multiple issues, but here's a placeholder.

**Comment by sethfitz** [comment]
* [x] Set up quay.io build for CGImap: https://quay.io/repository/openhistoricalmap/cgimap
* [x] Set up quay.io build for website: https://quay.io/repository/openhistoricalmap/website
* [x] Improve website container startup time (#13)
* [x] Create database instance (non-RDS, until #7) - `postgresql-10` on Ubuntu 18.04
* [x] Load OSM PostgreSQL functions
* [x] Initialize APIDB schema
* [x] Initialize iD owner
* [x] Create iD application entry
* [ ] Create RDS instance
* [-] ~Create CloudFormation stack~ determined too much effort vs return
* [ ] Set up Osmosis (minutely) replication
* [ ] Set up changeset replication
* [ ] Set up planet-dump-ng Planet generation

## Placeholder PostgreSQL instance

Ubuntu 18.04 LTS. @mojodna and @jimmyrocks have ssh access.

```bash
sudo apt install bundler libxml2-dev make postgresql-server-dev-10

# /etc/postgresql/10/main/postgresql.conf:
# listen_addresses = '*'
# /etc/postgresql/10/main/pg_hba.conf:
# host    all             all             0.0.0.0/0               md5

sudo -u postgres createdb openhistoricalmap
sudo -u postgres createuser -P openhistoricalmap
sudo service postgresql reload
sudo -u postgres psql -d openhistoricalmap -c "create extension btree_gist"

git clone https://github.com/openhistoricalmap/ohm-website
cd ohm-website
bundle install -j $(nproc)
export DATABASE_URL=<redacted>
rake db:migrate

cd ohm-website/db/functions
make
cd ../..
sudo -u postgres psql -d openhistoricalmap -c "CREATE FUNCTION maptile_for_point(int8, int8, int4) RETURNS int4 AS '$(pwd)/db/functions/libpgosm', 'maptile_for_point' LANGUAGE C STRICT"
sudo -u postgres psql -d openhistoricalmap -c "CREATE FUNCTION tile_for_point(int4, int4) RETURNS int8 AS '$(pwd)/db/functions/libpgosm', 'tile_for_point' LANGUAGE C STRICT"
sudo -u postgres psql -d openhistoricalmap -c "CREATE FUNCTION xid_to_int4(xid) RETURNS int4 AS '$(pwd)/db/functions/libpgosm', 'xid_to_int4' LANGUAGE C STRICT"
```

**Comment by sethfitz** [comment]
It's alive! http://openhistoricalmap-1936150974.us-east-1.elb.amazonaws.com

(Hand-built ECS + ALB configs for now.)

**Comment by danrademacher** [comment]
Last two items depend on #7
